### ISSUE TITLE
Curl not working

### ISSUE THREAD

**Issue by Nikoloutsos** [jimfilippou/opendelos-thief#1]
1. Copy clipboard by clicking curl button
2. Paste in terminal (Macbook)
3. Error and system error sound come out every 1s ;P

![image](https://user-images.githubusercontent.com/14034942/82759806-397a7b80-9df8-11ea-8dfe-1d88f69a7c7b.png)

**Comment by jimfilippou** [comment]
Thanks for your contribution my man! Will fix

**Comment by jimfilippou** [comment]
<img width="571" alt="Screenshot 2020-05-24 at 8 05 53 PM" src="https://user-images.githubusercontent.com/6877046/82760082-033dfb80-9dfa-11ea-96de-c924ee7c84d6.png">
Also 👆
